// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/3/2026, 3:20:35 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/workspace/electronic-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/electronic-web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/electronic-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/electronic-web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/electronic-web/plugins/**/*.{js,ts,mjs}","/workspace/electronic-web/composables/**/*.{js,ts,mjs}","/workspace/electronic-web/utils/**/*.{js,ts,mjs}","/workspace/electronic-web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/electronic-web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/workspace/electronic-web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/workspace/electronic-web/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;